import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'hr' | 'en';

type TranslationDictionary = Record<string, string>;

const translations: Record<Language, TranslationDictionary> = {
    hr: {
        'nav.platform': 'Platforma',
        'nav.history': 'Povijest',
        'nav.examiners': 'Ispitivači',
        'nav.customers': 'Kupci',
        'nav.settings': 'Postavke',
        'nav.analytics': 'Analitika',
        'nav.help': 'Pomoć',
        'nav.signOut': 'Odjava',
        'settings.language': 'Jezik',
        'settings.languageDescription': 'Odaberite jezik sučelja',
        'language.croatian': 'Hrvatski',
        'language.english': 'Engleski',
        'history.title': 'Povijest',
        'history.certifier': 'Certifikator',
        'history.createdBy': 'Kreirao',
        'history.constructionPart': 'Dio gradilišta',
        'history.formsCount': 'Broj obrazaca',
        'history.creationTime': 'Vrijeme kreiranja',
        'history.open': 'Otvori',
        'history.remove': 'Obriši',
        'history.searchPlaceholder': 'Traži dio gradilišta...',
        'history.noDataTitle': 'Nema povijesti',
        'history.noDataDesc': 'Izvezeni izvještaji pojavit će se ovdje.',
        'history.loading': 'Učitavanje...',
        'history.page': 'Stranica',
        'history.of': 'od',
        'exportDetails.title': 'Detalji izvoza',
        'exportDetails.info': 'Informacije',
        'exportDetails.remarks': 'Napomene i odstupanja',
        'exportDetails.certifier': 'Certifikator',
        'exportDetails.createdBy': 'Kreirao',
        'exportDetails.examinationDate': 'Datum ispitivanja',
        'exportDetails.creationTime': 'Vrijeme kreiranja',
        'exportDetails.drainage': 'Drenaza',
        'exportDetails.waterRemark': 'Napomena voda',
        'exportDetails.waterDeviation': 'Odstupanje voda',
        'exportDetails.airRemark': 'Napomena zrak',
        'exportDetails.airDeviation': 'Odstupanje zrak',
        'exportDetails.includedReports': 'Uključeni izvještaji',
        'exportDetails.ordinal': 'Redni broj',
        'exportDetails.type': 'Tip',
        'exportDetails.satisfies': 'Zadovoljava',
        'exportDetails.dionica': 'Dionica',
        'exportDetails.action': 'Akcija',
        'exportDetails.edit': 'Uredi',
        'exportDetails.download': 'Preuzmi',
        'exportDetails.exportWord': 'Izvoz Word',
        'exportDetails.exportPdf': 'Izvoz PDF',
        'exportDetails.exportAllPdf': 'Izvoz svih PDF',
        'exportDetails.water': 'Voda',
        'exportDetails.air': 'Zrak',
        'exportDetails.report': 'Izvještaj',
        'exportDetails.attachments': 'Prilozi',
        'exportDetails.selectAll': 'Označi sve',
        'exportDetails.exporting': 'Izvoz u tijeku...',
        'exportDetails.downloading': 'Preuzimanje...',
        'exportDetails.downloadFailed': 'Neuspjelo preuzimanje. Pokušajte ponovno.',
        'exportDetails.generatingPdf': 'Generiranje PDF izvoza...',
        'exportDetails.generatingWord': 'Generiranje Word dokumenta...',
        'exportDetails.exportFailed': 'Neuspjeli izvoz. Pokušajte ponovno.',
        'exportDetails.wordFailed': 'Neuspjeli izvoz Word dokumenta. Pokušajte ponovno.',
        'dashboard.welcome': 'Pozdrav',
        'dashboard.ready': 'Vaš generator je spreman.',
        'dashboard.totalCustomers': 'Ukupno kupaca',
        'dashboard.activeSites': 'Aktivna gradilišta',
        'dashboard.totalReports': 'Ukupno izvještaja',
        'dashboard.customersTable': 'Naručitelji',
        'dashboard.search': 'Pretraga...',
        'dashboard.addCustomer': 'Dodaj naručitelja',
        'dashboard.workOrder': 'Radni nalog',
        'dashboard.customer': 'Naručitelj',
        'dashboard.activeOrders': 'Aktivni radni nalozi',
        'dashboard.none': 'Nema',
        'dashboard.showMore': 'Prikaži više',
        'dashboard.showLess': 'Prikaži manje',
        'dashboard.loading': 'Učitavanje...',
        'dashboard.noCustomers': 'Nema kupaca',
        'dashboard.topCustomers': 'Naručitelji',
        'dashboard.examiners': 'Ispitivači',
        'dashboard.today': 'Danas',
        'dashboard.thisWeek': 'Ovaj tjedan',
        'common.yes': 'Da',
        'common.no': 'Ne',
        'common.edit': 'Uredi',
        'common.delete': 'Obriši',
        'examiners.title': 'Ispitivači',
        'examiners.subtitle': 'Upravljajte ispitivačima i njihovim akreditacijama.',
        'examiners.add': 'Dodaj ispitivača',
        'examiners.search': 'Pretraži ispitivače...',
        'examiners.fullName': 'Puno ime',
        'examiners.username': 'Korisničko ime',
        'examiners.email': 'Email',
        'examiners.accreditations': 'Akreditacije',
        'examiners.actions': 'Akcije',
        'examiners.loading': 'Učitavanje...',
        'examiners.noneFound': 'Nema pronađenih ispitivača',
        'examiners.noneDesc': 'Dodajte ispitivače kako biste upravljali njihovim akreditacijama i zadacima.',
        'examiners.accessDenied': 'Pristup odbijen',
        'examiners.accessDesc': 'Samo administratori mogu upravljati ispitivačima.',
        'examiners.admin': 'Administrator',
        'examiners.removeConfirm': 'Jeste li sigurni da želite ukloniti ovog ispitivača?',
        'examiners.dialog.new': 'Novi ispitivač',
        'examiners.dialog.edit': 'Uredi ispitivača',
        'examiners.dialog.firstName': 'Ime',
        'examiners.dialog.lastName': 'Prezime',
        'examiners.dialog.username': 'Korisničko ime',
        'examiners.dialog.title': 'Titula',
        'examiners.dialog.email': 'Email',
        'examiners.dialog.password': 'Lozinka',
        'examiners.dialog.passwordHint': '(ostavite prazno za zadržavanje postojeće)',
        'examiners.dialog.passwordPlaceholder': 'Unesite novu lozinku za promjenu',
        'examiners.dialog.admin': 'Administrator',
        'examiners.dialog.accreditations': 'Akreditacije',
        'examiners.dialog.cancel': 'Odustani',
        'examiners.dialog.save': 'Spremi',
        'examiners.dialog.saving': 'Spremanje...',
        'examiners.dialog.fillRequired': 'Molimo ispunite sva obavezna polja',
        'examiners.dialog.emailRequired': 'Email je obavezan za nove ispitivače',
        'examiners.dialog.passwordRequired': 'Lozinka je obavezna za nove ispitivače',
        'examiners.dialog.passwordTooShort': 'Lozinka mora imati najmanje 6 znakova',
        'examiners.dialog.accreditationRequired': 'Molimo odaberite barem jednu akreditaciju',
        'examiners.dialog.saveFailed': 'Spremanje ispitivača nije uspjelo',
        'customers.title': 'Kupci',
        'customers.new': 'Novi kupac',
        'customers.search': 'Pretraži kupce...',
        'customers.workOrder': 'Radni nalog',
        'customers.name': 'Naziv',
        'customers.location': 'Lokacija',
        'customers.address': 'Adresa',
        'customers.actions': 'Akcije',
        'customers.loading': 'Učitavanje...',
        'customers.none': 'Nema pronađenih kupaca.',
        'customers.showing': 'Prikazujem',
        'customers.to': 'do',
        'customers.of': 'od',
        'customers.results': 'rezultata',
        'customers.prev': 'Prethodna',
        'customers.next': 'Sljedeća',
        'customers.viewConstructions': 'Pogledaj gradilišta',
        'customers.edit': 'Uredi',
        'customers.deleteConfirm': 'Brisanje kupca će ukloniti sve povezane izvještaje. Nastaviti?',
        'reports.title': 'Izvještaji',
        'reports.dionica': 'Dionica',
        'reports.searchDionica': 'Traži dionicu...',
        'reports.type': 'Tip',
        'reports.status': 'Status',
        'reports.date': 'Datum',
        'reports.water': 'Voda',
        'reports.air': 'Zrak',
        'reports.satisfies': 'Zadovoljava',
        'reports.failed': 'Ne zadovoljava',
        'reports.noData': 'Nema izvještaja',
        'reports.deleteSelected': 'Obriši odabrano',
        'reports.newReport': 'Novi izvještaj',
        'reports.new': 'Novi',
        'reports.waterMethod': 'Metoda vodom',
        'reports.airMethod': 'Metoda zrakom',
        'reports.addSection': 'Dodaj sekciju',
        'reports.enterSectionName': 'Unesite naziv sekcije:',
        'reports.generateReports': 'Generiraj izvještaje',
        'reports.generate': 'Generiraj',
        'reports.exportSelected': 'Izvezi odabrano',
        'reports.exportAll': 'Izvezi sve',
        'reports.export': 'Izvezi',
        'reports.exportPdf': 'Izvezi PDF',
        'reports.edit': 'Uredi',
        'reports.delete': 'Obriši',
        'reports.draft': 'Nacrt',
        'reports.actions': 'Akcije',
        'common.all': 'Sve',
    },
    en: {
        'nav.platform': 'Platform',
        'nav.history': 'History',
        'nav.examiners': 'Examiners',
        'nav.customers': 'Customers',
        'nav.settings': 'Settings',
        'nav.analytics': 'Analytics',
        'nav.help': 'Help',
        'nav.signOut': 'Sign Out',
        'settings.language': 'Language',
        'settings.languageDescription': 'Choose the interface language',
        'language.croatian': 'Croatian',
        'language.english': 'English',
        'history.title': 'History',
        'history.certifier': 'Certifier',
        'history.createdBy': 'Created By',
        'history.constructionPart': 'Construction Part',
        'history.formsCount': 'Forms Count',
        'history.creationTime': 'Creation Time',
        'history.open': 'Open',
        'history.remove': 'Remove',
        'history.searchPlaceholder': 'Search construction part...',
        'history.noDataTitle': 'No history found',
        'history.noDataDesc': 'Exported reports and their history will appear here.',
        'history.loading': 'Loading...',
        'history.page': 'Page',
        'history.of': 'of',
        'exportDetails.title': 'Export Details',
        'exportDetails.info': 'Information',
        'exportDetails.remarks': 'Remarks & Deviations',
        'exportDetails.certifier': 'Certifier',
        'exportDetails.createdBy': 'Created By',
        'exportDetails.examinationDate': 'Examination Date',
        'exportDetails.creationTime': 'Creation Time',
        'exportDetails.drainage': 'Drainage',
        'exportDetails.waterRemark': 'Water Remark',
        'exportDetails.waterDeviation': 'Water Deviation',
        'exportDetails.airRemark': 'Air Remark',
        'exportDetails.airDeviation': 'Air Deviation',
        'exportDetails.includedReports': 'Included Reports',
        'exportDetails.ordinal': 'Ordinal',
        'exportDetails.type': 'Type',
        'exportDetails.satisfies': 'Satisfies',
        'exportDetails.dionica': 'Dionica',
        'exportDetails.action': 'Action',
        'exportDetails.edit': 'Edit',
        'exportDetails.download': 'Download',
        'exportDetails.exportWord': 'Export Word',
        'exportDetails.exportPdf': 'Export PDF',
        'exportDetails.exportAllPdf': 'Export All PDF',
        'exportDetails.water': 'Water',
        'exportDetails.air': 'Air',
        'exportDetails.report': 'Report',
        'exportDetails.attachments': 'Attachments',
        'exportDetails.selectAll': 'Select All',
        'exportDetails.exporting': 'Exporting...',
        'exportDetails.downloading': 'Downloading...',
        'exportDetails.downloadFailed': 'Failed to download. Please try again.',
        'exportDetails.generatingPdf': 'Generating PDF export...',
        'exportDetails.generatingWord': 'Generating Word document...',
        'exportDetails.exportFailed': 'Failed to export. Please try again.',
        'exportDetails.wordFailed': 'Failed to export Word document. Please try again.',
        'dashboard.welcome': 'Hello',
        'dashboard.ready': 'Your generator is ready.',
        'dashboard.totalCustomers': 'Total Customers',
        'dashboard.activeSites': 'Active Sites',
        'dashboard.totalReports': 'Total Reports',
        'dashboard.customersTable': 'Customers',
        'dashboard.search': 'Search...',
        'dashboard.addCustomer': 'Add customer',
        'dashboard.workOrder': 'Work Order',
        'dashboard.customer': 'Customer',
        'dashboard.activeOrders': 'Active Work Orders',
        'dashboard.none': 'None',
        'dashboard.showMore': 'Show more',
        'dashboard.showLess': 'Show less',
        'dashboard.loading': 'Loading...',
        'dashboard.noCustomers': 'No customers found',
        'dashboard.topCustomers': 'Top Customers',
        'dashboard.examiners': 'Examiners',
        'dashboard.today': 'Today',
        'dashboard.thisWeek': 'This week',
        'common.yes': 'Yes',
        'common.no': 'No',
        'examiners.title': 'Examiners',
        'examiners.subtitle': 'Manage examiners and their accreditations.',
        'examiners.add': 'Add Examiner',
        'examiners.search': 'Search examiners...',
        'examiners.fullName': 'Full Name',
        'examiners.username': 'Username',
        'examiners.email': 'Email',
        'examiners.accreditations': 'Accreditations',
        'examiners.actions': 'Actions',
        'examiners.loading': 'Loading...',
        'examiners.noneFound': 'No examiners found',
        'examiners.noneDesc': 'Add examiners to manage their accreditations and assignments.',
        'examiners.accessDenied': 'Access Denied',
        'examiners.accessDesc': 'Only administrators can manage examiners.',
        'examiners.admin': 'Administrator',
        'examiners.removeConfirm': 'Are you sure you want to remove this examiner?',
        'examiners.dialog.new': 'New Examiner',
        'examiners.dialog.edit': 'Edit Examiner',
        'examiners.dialog.firstName': 'First Name',
        'examiners.dialog.lastName': 'Last Name',
        'examiners.dialog.username': 'Username',
        'examiners.dialog.title': 'Title',
        'examiners.dialog.email': 'Email',
        'examiners.dialog.password': 'Password',
        'examiners.dialog.passwordHint': '(leave empty to keep current)',
        'examiners.dialog.passwordPlaceholder': 'Enter new password to change',
        'examiners.dialog.admin': 'Administrator',
        'examiners.dialog.accreditations': 'Accreditations',
        'examiners.dialog.cancel': 'Cancel',
        'examiners.dialog.save': 'Save',
        'examiners.dialog.saving': 'Saving...',
        'examiners.dialog.fillRequired': 'Please fill in all required fields',
        'examiners.dialog.emailRequired': 'Email is required for new examiners',
        'examiners.dialog.passwordRequired': 'Password is required for new examiners',
        'examiners.dialog.passwordTooShort': 'Password must be at least 6 characters long',
        'examiners.dialog.accreditationRequired': 'Please select at least one accreditation',
        'examiners.dialog.saveFailed': 'Failed to save examiner',
        'customers.title': 'Customers',
        'customers.new': 'New Customer',
        'customers.search': 'Search customers...',
        'customers.workOrder': 'Work Order',
        'customers.name': 'Name',
        'customers.location': 'Location',
        'customers.address': 'Address',
        'customers.actions': 'Actions',
        'customers.loading': 'Loading...',
        'customers.none': 'No customers found.',
        'customers.showing': 'Showing',
        'customers.to': 'to',
        'customers.of': 'of',
        'customers.results': 'results',
        'customers.prev': 'Previous',
        'customers.next': 'Next',
        'customers.viewConstructions': 'View Constructions',
        'customers.edit': 'Edit',
        'customers.deleteConfirm': 'Removing this customer will also remove all related reports. Continue?',
        'reports.title': 'Reports',
        'reports.dionica': 'Dionica',
        'reports.searchDionica': 'Search dionica...',
        'reports.type': 'Type',
        'reports.status': 'Status',
        'reports.date': 'Date',
        'reports.water': 'Water',
        'reports.air': 'Air',
        'reports.satisfies': 'Satisfies',
        'reports.failed': 'Failed',
        'reports.noData': 'No reports found',
        'reports.deleteSelected': 'Delete Selected',
        'reports.newReport': 'New Report',
        'reports.new': 'New',
        'reports.waterMethod': 'Water Method',
        'reports.airMethod': 'Air Method',
        'reports.addSection': 'Add Section',
        'reports.enterSectionName': 'Enter section name:',
        'reports.generateReports': 'Generate Reports',
        'reports.generate': 'Generate',
        'reports.exportSelected': 'Export Selected',
        'reports.exportAll': 'Export All',
        'reports.export': 'Export',
        'reports.exportPdf': 'Export PDF',
        'reports.edit': 'Edit',
        'reports.delete': 'Delete',
        'reports.draft': 'Draft',
        'reports.actions': 'Actions',
        'common.all': 'All',
    }
};

// Final clean overrides and additions
Object.assign(translations.hr, {
    'customers.postalCode': 'Poštanski broj',
    'customers.dateAdded': 'Datum dodavanja',
    'customers.save': 'Spremi',
    'customers.loadingForm': 'Učitavanje...',
    'customers.newTitle': 'Novi kupac',
    'customers.editTitle': 'Uredi kupca',
    'customers.placeholderWork': 'npr. 2023-001',
    'customers.placeholderName': 'Naziv kupca',
    'customers.placeholderLocation': 'Grad / Regija',
    'customers.placeholderAddress': 'Ulica i broj',
    'customers.placeholderPostal': 'Poštanski broj',
    'customers.deleteConfirm': 'Brisanje kupca će ukloniti sve povezane izvještaje. Nastaviti?',
    'customers.search': 'Pretraži kupce...',
    'customers.viewConstructions': 'Pogledaj gradilišta',
    'customers.next': 'Sljedeća',
    'constructions.title': 'Gradilišta',
    'constructions.new': 'Novo gradilište',
    'constructions.for': 'za',
    'constructions.search': 'Pretraži gradilišta...',
    'constructions.workOrder': 'Radni nalog',
    'constructions.name': 'Naziv',
    'constructions.location': 'Lokacija',
    'constructions.dateAdded': 'Datum dodavanja',
    'constructions.actions': 'Akcije',
    'constructions.viewReports': 'Pogledaj izvještaje',
    'constructions.edit': 'Uredi',
    'constructions.delete': 'Obriši',
    'constructions.deleteConfirm': 'Jeste li sigurni da želite obrisati ovo gradilište? Ovo će obrisati sve povezane izvještaje.',
    'constructions.none': 'Nema gradilišta.',
    'constructions.loading': 'Učitavanje...',
    'constructions.save': 'Spremi',
    'reports.date': 'Datum',
    'reports.type': 'Tip',
    'reports.dionica': 'Dionica',
    'reports.draft': 'Skica',
    'reports.status': 'Status',
    'reports.actions': 'Akcije',
    'reports.exportPdf': 'Izvoz PDF',
    'reports.edit': 'Uredi',
    'reports.delete': 'Obriši',
    'reports.noData': 'Nema izvješća za ovo gradilište.',
    'reports.satisfies': 'Zadovoljava',
    'reports.failed': 'Ne zadovoljava',
    'reports.new': 'Novo',
    'reports.generate': 'Generiraj',
    'reports.export': 'Izvoz'
});

Object.assign(translations.en, {
    'constructions.title': 'Construction Sites',
    'constructions.new': 'New Construction',
    'constructions.for': 'for',
    'constructions.search': 'Search constructions...',
    'constructions.workOrder': 'Work Order',
    'constructions.name': 'Name',
    'constructions.location': 'Location',
    'constructions.actions': 'Actions',
    'constructions.viewReports': 'View Reports',
    'constructions.edit': 'Edit',
    'constructions.delete': 'Delete',
    'constructions.deleteConfirm': 'Are you sure you want to delete this construction site? This will also delete all associated reports.',
    'constructions.none': 'No construction sites found.',
    'constructions.loading': 'Loading...',
    'constructions.save': 'Save',
    'constructions.newTitle': 'New Construction',
    'constructions.editTitle': 'Edit Construction',
    'constructions.placeholderWork': 'e.g., 2023-001-A',
    'constructions.placeholderName': 'Construction Site Name',
    'constructions.placeholderLocation': 'Site Location',
    'constructions.dateAdded': 'Date Added',
    'reports.title': 'Reports',
    'reports.deleteSelected': 'Delete Selected',
    'reports.newReport': 'New Report',
    'reports.delete': 'Delete',
    'reports.noData': 'No reports found for this construction site.',
    'reports.satisfies': 'Satisfies',
    'reports.failed': 'Failed'
});

Object.assign(translations.en, {
    'customers.postalCode': 'Postal Code',
    'customers.dateAdded': 'Date Added',
    'customers.save': 'Save',
    'customers.loadingForm': 'Loading...',
    'customers.newTitle': 'New Customer',
    'customers.editTitle': 'Edit Customer',
    'customers.placeholderWork': 'e.g., 2023-001',
    'customers.placeholderName': 'Customer Name',
    'customers.placeholderLocation': 'City / Region',
    'customers.placeholderAddress': 'Street Address',
    'customers.placeholderPostal': 'Postal Code',
    'customers.deleteConfirm': 'Removing this customer will also remove all related reports. Continue?',
    'customers.search': 'Search customers...',
    'customers.viewConstructions': 'View Constructions',
    'customers.next': 'Next',
    'constructions.title': 'Construction Sites',
    'constructions.for': 'for',
    'constructions.new': 'New Construction',
    'constructions.search': 'Search constructions...',
    'constructions.workOrder': 'Work Order',
    'constructions.name': 'Name',
    'constructions.location': 'Location',
    'constructions.actions': 'Actions',
    'constructions.viewReports': 'View Reports',
    'constructions.edit': 'Edit',
    'constructions.delete': 'Delete',
    'constructions.deleteConfirm': 'Are you sure you want to delete this construction site? This will also delete all associated reports.',
    'constructions.none': 'No construction sites found.'
});

// Clean overrides for constructions (HR/EN)
Object.assign(translations.hr, {
    'constructions.loading': 'Učitavanje...',
    'constructions.save': 'Spremi',
    'constructions.newTitle': 'Novo gradilište',
    'constructions.editTitle': 'Uredi gradilište',
    'constructions.placeholderWork': 'npr. 2023-001-A',
    'constructions.placeholderName': 'Naziv gradilišta',
    'constructions.placeholderLocation': 'Lokacija gradilišta'
});

Object.assign(translations.en, {
    'constructions.loading': 'Loading...',
    'constructions.save': 'Save',
    'constructions.newTitle': 'New Construction',
    'constructions.editTitle': 'Edit Construction',
    'constructions.placeholderWork': 'e.g., 2023-001-A',
    'constructions.placeholderName': 'Construction Site Name',
    'constructions.placeholderLocation': 'Site Location'
});

// Settings / Materials translations
Object.assign(translations.hr, {
    'materials.shaftTitle': 'Materijali za okna',
    'materials.pipeTitle': 'Materijali za cijevi',
    'materials.addShaft': 'Dodaj materijal okna',
    'materials.addPipe': 'Dodaj materijal cijevi',
    'materials.newShaft': 'Dodaj novi materijal okna',
    'materials.newPipe': 'Dodaj novi materijal cijevi',
    'materials.editShaft': 'Uredi materijal okna',
    'materials.editPipe': 'Uredi materijal cijevi',
    'materials.namePlaceholder': 'Naziv materijala',
    'materials.save': 'Spremi',
    'materials.cancel': 'Odustani',
    'materials.noneShaftTitle': 'Nema materijala za okna',
    'materials.nonePipeTitle': 'Nema materijala za cijevi',
    'materials.noneDesc': 'Dodajte materijale kako biste ih koristili u izvještajima.',
    'materials.edit': 'Uredi',
    'materials.remove': 'Ukloni',
    'materials.added': 'Materijal dodan.',
    'materials.updated': 'Materijal ažuriran.',
    'materials.removed': 'Materijal uklonjen.',
    'materials.deleteConfirm': 'Jeste li sigurni da želite ukloniti ovaj materijal?',
    'materials.restricted': 'Upravljanje materijalima je ograničeno na administratore.',
    'materials.inUseError': 'Materijal se koristi u izvještajima pa ga nije moguće ukloniti.',
    'materials.deleteDialogTitle': 'Potvrdi brisanje',
    'materials.deleteDialogMessage': 'Jeste li sigurni da želite obrisati ovaj materijal?',
    'materials.materialType': 'Vrsta materijala',
    'materials.materialName': 'Naziv materijala',
    'materials.deleteWarning': 'Ova radnja se ne može poništiti.',
    'materials.confirmDelete': 'Obriši materijal',
    'materials.shaftSingular': 'Materijal za okna',
    'materials.pipeSingular': 'Materijal za cijevi'
});

Object.assign(translations.en, {
    'materials.shaftTitle': 'Shaft Materials',
    'materials.pipeTitle': 'Pipe Materials',
    'materials.addShaft': 'Add shaft material',
    'materials.addPipe': 'Add pipe material',
    'materials.newShaft': 'Add new shaft material',
    'materials.newPipe': 'Add new pipe material',
    'materials.editShaft': 'Edit shaft material',
    'materials.editPipe': 'Edit pipe material',
    'materials.namePlaceholder': 'Material name',
    'materials.save': 'Save',
    'materials.cancel': 'Cancel',
    'materials.noneShaftTitle': 'No shaft materials found',
    'materials.nonePipeTitle': 'No pipe materials found',
    'materials.noneDesc': 'Add materials to use them in reports.',
    'materials.edit': 'Edit',
    'materials.remove': 'Remove',
    'materials.added': 'Material added successfully.',
    'materials.updated': 'Material updated successfully.',
    'materials.removed': 'Material removed successfully.',
    'materials.deleteConfirm': 'Are you sure you want to remove this material?',
    'materials.restricted': 'Material management is restricted to administrators.',
    'materials.inUseError': 'Material is used in reports and cannot be removed.',
    'materials.deleteDialogTitle': 'Confirm Deletion',
    'materials.deleteDialogMessage': 'Are you sure you want to delete this material?',
    'materials.materialType': 'Material type',
    'materials.materialName': 'Material name',
    'materials.deleteWarning': 'This action cannot be undone.',
    'materials.confirmDelete': 'Delete Material',
    'materials.shaftSingular': 'Shaft material',
    'materials.pipeSingular': 'Pipe material'
});

// Settings appearance translations
Object.assign(translations.hr, {
    'settings.appearance': 'Izgled',
    'settings.theme': 'Tema',
    'settings.themeDesc': 'Odaberite način prikaza',
    'settings.light': 'Svijetla',
    'settings.dark': 'Tamna',
    'settings.system': 'Sustav',
    'settings.primaryColor': 'Primarna boja',
    'settings.primaryColorDesc': 'Odaberite primarnu boju aplikacije'
});

Object.assign(translations.en, {
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Choose your display mode',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.primaryColor': 'Primary Color',
    'settings.primaryColorDesc': 'Choose the app\'s primary color'
});

// Analytics translations
Object.assign(translations.hr, {
    'analytics.title': 'Analitika',
    'analytics.subtitle': 'Pregled prolaznosti i trajanja ispitivanja.',
    'analytics.passFail': 'Prolaz vs. pad',
    'analytics.pass': 'Prolaz',
    'analytics.fail': 'Pad',
    'analytics.passRate': 'Postotak prolaza',
    'analytics.avgDuration': 'Prosječno trajanje ispitivanja',
    'analytics.water': 'Voda',
    'analytics.air': 'Zrak',
    'analytics.loading': 'Učitavanje analitike...',
    'analytics.error': 'Neuspjelo učitavanje analitike. Pokušajte ponovo.',
    'analytics.totalReports': 'Ukupno izvještaja',
    'analytics.activeCustomers': 'Ukupno kupaca',
    'analytics.constructionSites': 'Ukupno gradilišta',
    'analytics.recentActivity': 'Aktivni izvještaji',
    'analytics.thisWeek': 'Zadnjih 7 dana'
});

Object.assign(translations.en, {
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Overview of pass/fail and test durations.',
    'analytics.passFail': 'Pass vs Fail',
    'analytics.pass': 'Pass',
    'analytics.fail': 'Fail',
    'analytics.passRate': 'Pass rate',
    'analytics.avgDuration': 'Average Test Duration',
    'analytics.water': 'Water',
    'analytics.air': 'Air',
    'analytics.loading': 'Loading analytics...',
    'analytics.error': 'Failed to load analytics. Please try again.',
    'analytics.totalReports': 'Total Reports',
    'analytics.activeCustomers': 'Total Customers',
    'analytics.constructionSites': 'Construction Sites',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.thisWeek': 'Last 7 days'
});

// Report form translations
Object.assign(translations.hr, {
    'reports.form.airTitleNew': 'Novi zapis zraka',
    'reports.form.waterTitleNew': 'Novi zapis vode',
    'reports.form.editTitle': 'Uredi izvještaj',
    'reports.form.step1Desc': 'Korak 1: Parametri i dimenzije',
    'reports.form.step2Desc': 'Korak 2: Mjerenja i rezultati',
    'reports.form.stepper.parameters': 'Parametri',
    'reports.form.stepper.measurements': 'Mjerenja',
    'reports.form.generalInfo': 'Opće informacije',
    'reports.form.structureType': 'Tip strukture',
    'reports.form.dimensions': 'Dimenzije',
    'reports.form.pressureTime': 'Pritisak i vrijeme',
    'reports.form.remarksSection': 'Napomene',
    'reports.form.measurementsSection': 'Mjerenja',
    'reports.form.notesSection': 'Bilješke',
    'reports.form.calculatedResults': 'Izračunati rezultati',
    'reports.form.status': 'Status',
    'reports.form.satisfies': 'ZADOVOLJAVA',
    'reports.form.failed': 'NE ZADOVOLJAVA',
    'reports.form.exportPdf': 'Izvoz PDF',
    'reports.form.saveAndNew': 'Spremi i novi',
    'reports.form.nextStep': 'Sljedeći korak',
    'reports.form.prevStep': 'Prethodni korak',
    'reports.form.saveReport': 'Spremi izvještaj',
    'reports.form.saveSuccess': 'Izvještaj spremljen. Spreman za novi unos.',
    'reports.form.loadError': 'Neuspjelo učitavanje izvještaja',
    'reports.form.saveError': 'Spremanje izvještaja nije uspjelo',
    'reports.form.examProcedure': 'Postupak ispitivanja',
    'reports.form.selectProcedure': 'Odaberite postupak',
    'reports.form.selectMaterial': 'Odaberite materijal',
    'reports.form.dionica': 'Dionica',
    'reports.form.examDate': 'Datum ispitivanja',
    'reports.form.temperature': 'Temperatura (°C)',
    'reports.form.draftType': 'Shema',
    'reports.form.materialType': 'Vrsta okna',
    'reports.form.shaftOnly': 'Samo okno',
    'reports.form.round': 'Okruglo',
    'reports.form.rectangular': 'Pravokutno',
    'reports.form.paneDiameterM': 'Promjer okna (m)',
    'reports.form.paneWidthM': 'Pirina okna (m)',
    'reports.form.paneLengthM': 'Dužina okna (m)',
    'reports.form.pipeDiameterM': 'Promjer cijevi (m)',
    'reports.form.pipeLengthM': 'Dužina cijevi (m)',
    'reports.form.startPressure': 'Početni tlak (mbar)',
    'reports.form.endPressure': 'Završni tlak (mbar)',
    'reports.form.startTime': 'Početak',
    'reports.form.endTime': 'Kraj',
    'reports.form.remarkLabel': 'Napomena',
    'reports.form.remarkPlaceholder': 'Unesite napomene...',
    'reports.form.deviationLabel': 'Odstupanje',
    'reports.form.deviationPlaceholder': 'Unesite odstupanja od standarda...',
    'reports.form.pressureLoss': 'Gubitak tlaka',
    'reports.form.allowedLoss': 'Dopušteni gubitak',
    'reports.form.requiredTime': 'Vrijeme ispitivanja',
    'reports.form.dionicaLabel': 'Dionica',
    'reports.form.dionicaPlaceholder': 'Unesite naziv dionice',
    'reports.form.dionicaRequired': 'Dionica je obavezna',
    'reports.form.details': 'Detalji',
    'reports.form.schemeLabel': 'Shema',
    'reports.form.schemeA': 'Shema A â€“ Ispitivanje okna',
    'reports.form.schemeB': 'Shema B â€“ Ispitivanje okna i cijelovoda',
    'reports.form.schemeC': 'Shema C â€“ Ispitivanje cijelovoda',
    'reports.form.schemeD': 'Shema D â€“ Ispitivanje slivnika',
    'reports.form.schemeE': 'Shema E â€“ Ispitivanje slivnika i cijelovoda',
    'reports.form.gullyType': 'Vrsta slivnika',
    'reports.form.shaftType': 'Vrsta okna',
    'reports.form.gullyMaterial': 'Materijal slivnika',
    'reports.form.shaftMaterial': 'Materijal okna',
    'reports.form.standardMaterial': 'Standardni materijal',
    'reports.form.pipeMaterial': 'Materijal cijevi',
    'reports.form.standardPipe': 'Standardna cijev',
    'reports.form.paneDiameterMm': 'Promjer okna (mm)',
    'reports.form.paneWidthCm': 'Širina okna (cm)',
    'reports.form.paneLengthCm': 'Dužina okna (cm)',
    'reports.form.paneHeightCm': 'Visina okna (cm)',
    'reports.form.gullyDiameter': 'Promjer slivnika (mm)',
    'reports.form.gullyWidth': 'Širina slivnika (cm)',
    'reports.form.gullyLength': 'Dužina slivnika (cm)',
    'reports.form.gullyHeight': 'Visina slivnika (cm)',
    'reports.form.shaftHeight': 'Visina okna (cm)',
    'reports.form.mainPipeDiameter': 'Promjer glavne cijevi (mm)',
    'reports.form.channelWidth': 'Širina kanala (cm)',
    'reports.form.channelLength': 'Dužina kanala (cm)',
    'reports.form.channelHeight': 'Visina kanala (cm)',
    'reports.form.roHeight': 'Ro visina (cm)',
    'reports.form.waterHeight': 'Visina vode (cm)',
    'reports.form.duration': 'Trajanje (hh:mm:ss)',
    'reports.form.stabilizationTime': 'Vrijeme stabilizacije (mm:ss)',
    'reports.form.saturationTime': 'Vrijeme saturacije (hh:mm)',
    'reports.form.pipeDiameterMm': 'Promjer cijevi (mm)',
    'reports.form.pipeLengthMeters': 'Dužina cijevi (m)',
    'reports.form.slope': 'Nagib (%)',
    'reports.form.depositionalHeight': 'Visina taloženja (m)',
    'reports.form.startWaterLevel': 'Početna razina vode (mm)',
    'reports.form.endWaterLevel': 'Završna razina vode (mm)',
    'reports.form.waterLoss': 'Gubitak vode',
    'reports.form.volumeLoss': 'Gubitak volumena',
    'reports.form.totalWettedArea': 'Ukupna mokra površina',
    'reports.form.wettedShaftSurface': 'Mokra površina okna',
    'reports.form.wettedPipeSurface': 'Mokra površina cijevi',
    'reports.form.allowedLossLiters': 'Dopušteni gubitak (l)',
    'reports.form.allowedLossMm': 'Dopušteni gubitak (mm)',
    'reports.form.hydrostaticHeight': 'Hidrostatska visina',
    'reports.form.result': 'Rezultat',
    'reports.form.waterLossUnitMm': 'mm',
    'reports.form.volumeLossUnit': 'l',
    'reports.form.resultUnit': 'l/m^2'
});

Object.assign(translations.en, {
    'reports.form.airTitleNew': 'New Air Test Report',
    'reports.form.waterTitleNew': 'New Water Test Report',
    'reports.form.editTitle': 'Edit Report',
    'reports.form.step1Desc': 'Step 1: Parameters & Dimensions',
    'reports.form.step2Desc': 'Step 2: Measurements & Results',
    'reports.form.stepper.parameters': 'Parameters',
    'reports.form.stepper.measurements': 'Measurements',
    'reports.form.generalInfo': 'General Info',
    'reports.form.structureType': 'Structure Type',
    'reports.form.dimensions': 'Dimensions',
    'reports.form.pressureTime': 'Pressure & Time',
    'reports.form.remarksSection': 'Remarks',
    'reports.form.measurementsSection': 'Measurements',
    'reports.form.notesSection': 'Notes',
    'reports.form.calculatedResults': 'Calculated Results',
    'reports.form.status': 'Status',
    'reports.form.satisfies': 'SATISFIES',
    'reports.form.failed': 'FAILED',
    'reports.form.exportPdf': 'Export PDF',
    'reports.form.saveAndNew': 'Save & New',
    'reports.form.nextStep': 'Next Step',
    'reports.form.prevStep': 'Previous Step',
    'reports.form.saveReport': 'Save Report',
    'reports.form.saveSuccess': 'Report saved. Ready for next entry.',
    'reports.form.loadError': 'Failed to load report',
    'reports.form.saveError': 'Failed to save report',
    'reports.form.examProcedure': 'Examination Procedure',
    'reports.form.selectProcedure': 'Select procedure',
    'reports.form.selectMaterial': 'Select material',
    'reports.form.details': 'Details',
    'reports.form.dionica': 'Section',
    'reports.form.examDate': 'Examination Date',
    'reports.form.temperature': 'Temperature (Â°C)',
    'reports.form.draftType': 'Draft Type',
    'reports.form.materialType': 'Material Type',
    'reports.form.shaftOnly': 'Shaft only',
    'reports.form.round': 'Round',
    'reports.form.rectangular': 'Rectangular',
    'reports.form.paneDiameterM': 'Pane Diameter (m)',
    'reports.form.paneWidthM': 'Pane Width (m)',
    'reports.form.paneLengthM': 'Pane Length (m)',
    'reports.form.pipeDiameterM': 'Pipe Diameter (m)',
    'reports.form.pipeLengthM': 'Pipe Length (m)',
    'reports.form.startPressure': 'Start Pressure (mbar)',
    'reports.form.endPressure': 'End Pressure (mbar)',
    'reports.form.startTime': 'Start Time',
    'reports.form.endTime': 'End Time',
    'reports.form.remarkLabel': 'Remark',
    'reports.form.remarkPlaceholder': 'Enter any remarks...',
    'reports.form.deviationLabel': 'Deviation',
    'reports.form.deviationPlaceholder': 'Enter any deviations from standard...',
    'reports.form.pressureLoss': 'Pressure Loss',
    'reports.form.allowedLoss': 'Allowed Loss',
    'reports.form.requiredTime': 'Required Time',
    'reports.form.dionicaLabel': 'Section',
    'reports.form.dionicaPlaceholder': 'Enter section name',
    'reports.form.dionicaRequired': 'Section is required',
    'reports.form.schemeLabel': 'Scheme',
    'reports.form.schemeA': 'Scheme A â€“ Shaft test',
    'reports.form.schemeB': 'Scheme B â€“ Shaft and pipeline test',
    'reports.form.schemeC': 'Scheme C â€“ Pipeline test',
    'reports.form.schemeD': 'Scheme D â€“ Gully test',
    'reports.form.schemeE': 'Scheme E â€“ Gully and pipeline test',
    'reports.form.gullyType': 'Gully Type',
    'reports.form.shaftType': 'Shaft Type',
    'reports.form.gullyMaterial': 'Gully Material',
    'reports.form.shaftMaterial': 'Shaft Material',
    'reports.form.standardMaterial': 'Standard Material',
    'reports.form.pipeMaterial': 'Pipe Material',
    'reports.form.standardPipe': 'Standard Pipe',
    'reports.form.paneDiameterMm': 'Pane Diameter (mm)',
    'reports.form.paneWidthCm': 'Pane Width (cm)',
    'reports.form.paneLengthCm': 'Pane Length (cm)',
    'reports.form.paneHeightCm': 'Shaft Height (cm)',
    'reports.form.gullyDiameter': 'Gully Diameter (mm)',
    'reports.form.gullyWidth': 'Gully Width (cm)',
    'reports.form.gullyLength': 'Gully Length (cm)',
    'reports.form.gullyHeight': 'Gully Height (cm)',
    'reports.form.shaftHeight': 'Shaft Height (cm)',
    'reports.form.mainPipeDiameter': 'Main Pipe Diameter (mm)',
    'reports.form.channelWidth': 'Channel Width (cm)',
    'reports.form.channelLength': 'Channel Length (cm)',
    'reports.form.channelHeight': 'Channel Height (cm)',
    'reports.form.roHeight': 'Ro Height (cm)',
    'reports.form.waterHeight': 'Water Height (cm)',
    'reports.form.duration': 'Duration (hh:mm:ss)',
    'reports.form.stabilizationTime': 'Stabilization Time (mm:ss)',
    'reports.form.saturationTime': 'Saturation Time (hh:mm)',
    'reports.form.pipeDiameterMm': 'Pipe Diameter (mm)',
    'reports.form.pipeLengthMeters': 'Pipe Length (m)',
    'reports.form.slope': 'Slope (%)',
    'reports.form.depositionalHeight': 'Depositional Height (m)',
    'reports.form.startWaterLevel': 'Start Water Level (mm)',
    'reports.form.endWaterLevel': 'End Water Level (mm)',
    'reports.form.waterLoss': 'Water Loss',
    'reports.form.volumeLoss': 'Volume Loss',
    'reports.form.totalWettedArea': 'Total Wetted Area',
    'reports.form.wettedShaftSurface': 'Wetted Shaft Surface',
    'reports.form.wettedPipeSurface': 'Wetted Pipe Surface',
    'reports.form.allowedLossLiters': 'Allowed Loss (l)',
    'reports.form.allowedLossMm': 'Allowed Loss (mm)',
    'reports.form.hydrostaticHeight': 'Hydrostatic Height',
    'reports.form.result': 'Result',
    'reports.form.waterLossUnitMm': 'mm',
    'reports.form.volumeLossUnit': 'l',
    'reports.form.resultUnit': 'l/m^2'
});

// Clean HR overrides for report forms (fix mojibake)
Object.assign(translations.hr, {
    'reports.form.editTitle': 'Uredi izvještaj',
    'reports.form.generalInfo': 'Opće informacije',
    'reports.form.notesSection': 'Bilješke',
    'reports.form.calculatedResults': 'Izračunati rezultati',
    'reports.form.nextStep': 'Sljedeći korak',
    'reports.form.saveReport': 'Spremi izvještaj',
    'reports.form.saveSuccess': 'Izvještaj spremljen. Spreman za novi unos.',
    'reports.form.loadError': 'Neuspjelo učitavanje izvještaja',
    'reports.form.temperature': 'Temperatura (°C)',
    'reports.form.paneWidthM': 'Širina okna (m)',
    'reports.form.paneLengthM': 'Dužina okna (m)',
    'reports.form.pipeLengthM': 'Dužina cijevi (m)',
    'reports.form.startPressure': 'Početni tlak (mbar)',
    'reports.form.endPressure': 'Završni tlak (mbar)',
    'reports.form.startTime': 'Početak',
    'reports.form.allowedLoss': 'Dopušteni gubitak',
    'reports.form.schemeA': 'Shema A – Ispitivanje okna',
    'reports.form.schemeB': 'Shema B – Ispitivanje okna i cijelovoda',
    'reports.form.schemeC': 'Shema C – Ispitivanje cijelovoda',
    'reports.form.schemeD': 'Shema D – Ispitivanje slivnika',
    'reports.form.schemeE': 'Shema E – Ispitivanje slivnika i cijelovoda',
    'reports.form.paneWidthCm': 'Širina okna (cm)',
    'reports.form.paneLengthCm': 'Dužina okna (cm)',
    'reports.form.gullyWidth': 'Širina slivnika (cm)',
    'reports.form.gullyLength': 'Dužina slivnika (cm)',
    'reports.form.channelWidth': 'Širina kanala (cm)',
    'reports.form.channelLength': 'Dužina kanala (cm)',
    'reports.form.pipeLengthMeters': 'Dužina cijevi (m)',
    'reports.form.depositionalHeight': 'Visina taloženja (m)',
    'reports.form.startWaterLevel': 'Početna razina vode (mm)',
    'reports.form.endWaterLevel': 'Završna razina vode (mm)',
    'reports.form.totalWettedArea': 'Ukupna mokra površina',
    'reports.form.wettedShaftSurface': 'Mokra površina okna',
    'reports.form.wettedPipeSurface': 'Mokra površina cijevi',
    'reports.form.allowedLossLiters': 'Dopušteni gubitak (l)',
    'reports.form.allowedLossMm': 'Dopušteni gubitak (mm)',
    'reports.form.resultUnit': 'l/m²'
});

// Report method labels
Object.assign(translations.hr, {
    'reports.waterMethod': 'Metoda vode',
    'reports.airMethod': 'Metoda zraka'
});
Object.assign(translations.en, {
    'reports.waterMethod': 'Water Method',
    'reports.airMethod': 'Air Method'
});

// Export dialog translations
Object.assign(translations.hr, {
    'export.optionsTitle': 'Opcije izvoza izvještaja',
    'export.selectReports': 'Odaberite izvještaje za izvoz',
    'export.selectAll': 'Odaberi sve',
    'export.deselectAll': 'Poništi odabir',
    'export.selected': 'odabrano',
    'export.constructionPart': 'Dio Građevine',
    'export.constructionPartPlaceholder': 'npr. Zgrada 1',
    'export.drainage': 'Drenaža',
    'export.drainagePlaceholder': 'Tip sustava...',
    'export.remark': 'Napomena',
    'export.remarkPlaceholder': 'Napomene...',
    'export.deviation': 'Odstupanje',
    'export.deviationPlaceholder': 'Odstupanja od norme...',
    'export.certifierName': 'Certifikator',
    'export.certifierPlaceholder': 'Ime i prezime certifikatora',
    'export.attachments': 'Prilozi',
    'export.attachmentsHelp': 'Dodajte fotografije ili PDF dokumente koji će biti priloženi izvještaju',
    'export.cancel': 'Odustani',
    'export.exporting': 'Izvoz u tijeku...',
    'export.exportReport': 'Izvezi izvještaj'
});

Object.assign(translations.en, {
    'export.optionsTitle': 'Export Report Options',
    'export.selectReports': 'Select Reports to Export',
    'export.selectAll': 'Select All',
    'export.deselectAll': 'Deselect All',
    'export.selected': 'selected',
    'export.constructionPart': 'Construction Part',
    'export.constructionPartPlaceholder': 'e.g. Phase 1',
    'export.drainage': 'Drainage',
    'export.drainagePlaceholder': 'System type...',
    'export.remark': 'Remark',
    'export.remarkPlaceholder': 'Notes...',
    'export.deviation': 'Deviation',
    'export.deviationPlaceholder': 'Norm deviations...',
    'export.certifierName': 'Certifier Name',
    'export.certifierPlaceholder': 'Name of the person certifying...',
    'export.attachments': 'Attachments',
    'export.attachmentsHelp': 'Add photos or PDFs to attach to the report',
    'export.cancel': 'Cancel',
    'export.exporting': 'Exporting...',
    'export.exportReport': 'Export Report'
});

// Clean HR overrides for report forms (accents)
Object.assign(translations.hr, {
    'reports.form.editTitle': 'Uredi izvještaj',
    'reports.form.generalInfo': 'Opće informacije',
    'reports.form.notesSection': 'Bilješke',
    'reports.form.calculatedResults': 'Izračunati rezultati',
    'reports.form.nextStep': 'Sljedeći korak',
    'reports.form.saveReport': 'Spremi izvještaj',
    'reports.form.saveSuccess': 'Izvještaj spremljen. Spreman za novi unos.',
    'reports.form.loadError': 'Neuspjelo učitavanje izvještaja',
    'reports.form.temperature': 'Temperatura (°C)',
    'reports.form.paneWidthM': 'Širina okna (m)',
    'reports.form.paneLengthM': 'Dužina okna (m)',
    'reports.form.pipeLengthM': 'Dužina cijevi (m)',
    'reports.form.startPressure': 'Početni tlak (mbar)',
    'reports.form.endPressure': 'Završni tlak (mbar)',
    'reports.form.startTime': 'Početak',
    'reports.form.allowedLoss': 'Dopušteni gubitak',
    'reports.form.schemeA': 'Shema A – Ispitivanje okna',
    'reports.form.schemeB': 'Shema B – Ispitivanje okna i cijelovoda',
    'reports.form.schemeC': 'Shema C – Ispitivanje cijelovoda',
    'reports.form.schemeD': 'Shema D – Ispitivanje slivnika',
    'reports.form.schemeE': 'Shema E – Ispitivanje slivnika i cijelovoda',
    'reports.form.paneWidthCm': 'Širina okna (cm)',
    'reports.form.paneLengthCm': 'Dužina okna (cm)',
    'reports.form.gullyWidth': 'Širina slivnika (cm)',
    'reports.form.gullyLength': 'Dužina slivnika (cm)',
    'reports.form.channelWidth': 'Širina kanala (cm)',
    'reports.form.channelLength': 'Dužina kanala (cm)',
    'reports.form.pipeLengthMeters': 'Dužina cijevi (m)',
    'reports.form.depositionalHeight': 'Visina taloženja (m)',
    'reports.form.startWaterLevel': 'Početna razina vode (mm)',
    'reports.form.endWaterLevel': 'Završna razina vode (mm)',
    'reports.form.totalWettedArea': 'Ukupna mokra površina',
    'reports.form.wettedShaftSurface': 'Mokra površina okna',
    'reports.form.wettedPipeSurface': 'Mokra površina cijevi',
    'reports.form.allowedLossLiters': 'Dopušteni gubitak (l)',
    'reports.form.allowedLossMm': 'Dopušteni gubitak (mm)',
    'reports.form.resultUnit': 'l/m²'
});

// Help translations
Object.assign(translations.hr, {
    'help.title': 'Pomoć',
    'help.comingSoon': 'Pomoć i dokumentacija stižu uskoro...',
    'help.tabs.faq': 'Najčešća pitanja',
    'help.tabs.support': 'Podrška',
    'help.support.title': 'Zahtjev za podršku',
    'help.support.subtitle': 'Pošaljite nam svoj zahtjev za promjenom, prijavu greške ili prijedlog nove značajke',
    'help.support.requestType': 'Tip zahtjeva',
    'help.support.requestType.placeholder': 'Odaberite tip zahtjeva',
    'help.support.requestType.changeRequest': 'Zahtjev za promjenom',
    'help.support.requestType.bug': 'Prijava greške',
    'help.support.requestType.feature': 'Prijedlog značajke',
    'help.support.title.label': 'Naslov',
    'help.support.title.placeholder': 'Kratki opis problema ili zahtjeva',
    'help.support.description.label': 'Opis',
    'help.support.description.placeholder': 'Detaljno opišite svoj zahtjev, grešku ili prijedlog...',
    'help.support.attachments.label': 'Prilozi',
    'help.support.attachments.help': 'Priložite slike ili dokumente (maks. 5 MB po datoteci)',
    'help.support.attachments.button': 'Odaberi datoteke',
    'help.support.attachments.selected': 'odabrano',
    'help.support.submit': 'Pošalji zahtjev',
    'help.support.submitting': 'Šaljem...',
    'help.support.success': 'Zahtjev uspješno poslan!',
    'help.support.error': 'Greška prilikom slanja zahtjeva. Pokušajte ponovno.',
    'help.support.validation.requestType': 'Molimo odaberite tip zahtjeva',
    'help.support.validation.title': 'Molimo unesite naslov',
    'help.support.validation.description': 'Molimo unesite opis',
    'help.support.validation.fileSize': 'Datoteka je prevelika (maks. 5 MB)',
});
Object.assign(translations.en, {
    'help.title': 'Help',
    'help.comingSoon': 'Help and documentation coming soon...',
    'help.tabs.faq': 'FAQ',
    'help.tabs.support': 'Support',
    'help.support.title': 'Support Request',
    'help.support.subtitle': 'Send us your change request, bug report, or feature suggestion',
    'help.support.requestType': 'Request Type',
    'help.support.requestType.placeholder': 'Select request type',
    'help.support.requestType.changeRequest': 'Change Request',
    'help.support.requestType.bug': 'Bug Report',
    'help.support.requestType.feature': 'Feature Request',
    'help.support.title.label': 'Title',
    'help.support.title.placeholder': 'Brief description of the issue or request',
    'help.support.description.label': 'Description',
    'help.support.description.placeholder': 'Describe your request, bug, or suggestion in detail...',
    'help.support.attachments.label': 'Attachments',
    'help.support.attachments.help': 'Attach images or documents (max. 5 MB per file)',
    'help.support.attachments.button': 'Choose files',
    'help.support.attachments.selected': 'selected',
    'help.support.submit': 'Submit Request',
    'help.support.submitting': 'Sending...',
    'help.support.success': 'Request sent successfully!',
    'help.support.error': 'Error sending request. Please try again.',
    'help.support.validation.requestType': 'Please select a request type',
    'help.support.validation.title': 'Please enter a title',
    'help.support.validation.description': 'Please enter a description',
    'help.support.validation.fileSize': 'File is too large (max. 5 MB)',
});

// Common
Object.assign(translations.hr, {
    'common.back': 'Natrag'
});
Object.assign(translations.en, {
    'common.back': 'Back',
    'common.edit': 'Edit',
    'common.delete': 'Delete'
});

interface LanguageContextValue {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const stored = localStorage.getItem('language') as Language | null;
        return stored || 'hr';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
    }, [language]);

    const setLanguage = (lang: Language) => setLanguageState(lang);

    const t = (key: string) => translations[language][key] || translations.hr[key] || key;

    const value = useMemo(() => ({ language, setLanguage, t }), [language]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
    return ctx;
};








