import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'hr' | 'en';

type TranslationDictionary = Record<string, string>;

const translations: Record<Language, TranslationDictionary> = {
    hr: {
        'nav.platform': 'Platforma',
        'nav.history': 'Povijest',
        'nav.examiners': 'Ispitivači',
        'nav.customers': 'Naručitelji',
        'nav.settings': 'Postavke',
        'nav.analytics': 'Analitika',
        'nav.help': 'Pomoć',
        'nav.signOut': 'Odjava',
        'settings.language': 'Jezik',
        'settings.languageDescription': 'Odaberite jezik sučelja',
        'language.croatian': 'Hrvatski',
        'language.english': 'Engleski',
        'history.title': 'Povijest',
        'history.certifier': 'Certifikator',
        'history.createdBy': 'Kreirao',
        'history.constructionPart': 'Dio gradilišta',
        'history.formsCount': 'Broj obrazaca',
        'history.creationTime': 'Vrijeme kreiranja',
        'history.open': 'Otvori',
        'history.remove': 'Obriši',
        'history.searchPlaceholder': 'Traži dio gradilišta...',
        'history.noDataTitle': 'Nema povijesti',
        'history.noDataDesc': 'Izvezeni izvještaji pojavit će se ovdje.',
        'history.loading': 'Učitavanje...',
        'history.allUsers': 'Svi korisnici',
        'history.page': 'Stranica',
        'history.of': 'od',
        'exportDetails.title': 'Detalji izvoza',
        'exportDetails.info': 'Informacije',
        'exportDetails.remarks': 'Napomene i odstupanja',
        'exportDetails.certifier': 'Certifikator',
        'exportDetails.createdBy': 'Kreirao',
        'exportDetails.examinationDate': 'Datum ispitivanja',
        'exportDetails.creationTime': 'Vrijeme kreiranja',
        'exportDetails.drainage': 'Drenaza',
        'exportDetails.waterRemark': 'Napomena voda',
        'exportDetails.waterDeviation': 'Odstupanje voda',
        'exportDetails.airRemark': 'Napomena zrak',
        'exportDetails.airDeviation': 'Odstupanje zrak',
        'exportDetails.includedReports': 'Uključeni izvještaji',
        'exportDetails.ordinal': 'Redni broj',
        'exportDetails.type': 'Tip',
        'exportDetails.satisfies': 'Zadovoljava',
        'exportDetails.dionica': 'Dionica',
        'exportDetails.action': 'Akcija',
        'exportDetails.edit': 'Uredi',
        'exportDetails.download': 'Preuzmi',
        'exportDetails.exportWord': 'Izvoz Word',
        'exportDetails.exportPdf': 'Izvoz PDF',
        'exportDetails.exportAllPdf': 'Izvoz svih PDF',
        'exportDetails.water': 'Voda',
        'exportDetails.air': 'Zrak',
        'exportDetails.report': 'Izvještaj',
        'exportDetails.attachments': 'Prilozi',
        'exportDetails.selectAll': 'Označi sve',
        'exportDetails.exporting': 'Izvoz u tijeku...',
        'exportDetails.downloading': 'Preuzimanje...',
        'exportDetails.downloadFailed': 'Neuspjelo preuzimanje. Pokušajte ponovno.',
        'exportDetails.generatingPdf': 'Generiranje PDF izvoza...',
        'exportDetails.generatingWord': 'Generiranje Word dokumenta...',
        'exportDetails.exportFailed': 'Neuspjeli izvoz. Pokušajte ponovno.',
        'exportDetails.wordFailed': 'Neuspjeli izvoz Word dokumenta. Pokušajte ponovno.',
        'dashboard.welcome': 'Pozdrav',
        'dashboard.ready': 'Vaš generator je spreman.',
        'dashboard.totalCustomers': 'Ukupno naručitelja',
        'dashboard.activeSites': 'Aktivna gradilišta',
        'dashboard.totalReports': 'Ukupno izvještaja',
        'dashboard.customersTable': 'Naručitelji',
        'dashboard.search': 'Pretraga...',
        'dashboard.addCustomer': 'Dodaj naručitelja',
        'dashboard.workOrder': 'Radni nalog',
        'dashboard.customer': 'Naručitelj',
        'dashboard.activeOrders': 'Aktivni radni nalozi',
        'dashboard.none': 'Nema',
        'dashboard.showMore': 'Prikaži više',
        'dashboard.showLess': 'Prikaži manje',
        'dashboard.loading': 'Učitavanje...',
        'dashboard.noCustomers': 'Nema naručitelja',
        'dashboard.topCustomers': 'Naručitelji',
        'dashboard.examiners': 'Ispitivači',
        'dashboard.today': 'Danas',
        'dashboard.thisWeek': 'Ovaj tjedan',
        'common.yes': 'Da',
        'common.no': 'Ne',
        'common.edit': 'Uredi',
        'common.delete': 'Obriši',
        'common.you': 'Vi',
        'examiners.title': 'Ispitivači',
        'examiners.subtitle': 'Upravljajte ispitivačima i njihovim akreditacijama.',
        'examiners.add': 'Dodaj ispitivača',
        'examiners.search': 'Pretraži ispitivače...',
        'examiners.fullName': 'Puno ime',
        'examiners.username': 'Korisničko ime',
        'examiners.email': 'Email',
        'examiners.accreditations': 'Akreditacije',
        'examiners.actions': 'Akcije',
        'examiners.loading': 'Učitavanje...',
        'examiners.noneFound': 'Nema pronađenih ispitivača',
        'examiners.noneDesc': 'Dodajte ispitivače kako biste upravljali njihovim akreditacijama i zadacima.',
        'examiners.accessDenied': 'Pristup odbijen',
        'examiners.accessDesc': 'Samo administratori mogu upravljati ispitivačima.',
        'examiners.admin': 'Administrator',
        'examiners.removeConfirm': 'Jeste li sigurni da želite ukloniti ovog ispitivača?',
        'examiners.dialog.new': 'Novi ispitivač',
        'examiners.dialog.edit': 'Uredi ispitivača',
        'examiners.dialog.firstName': 'Ime',
        'examiners.dialog.lastName': 'Prezime',
        'examiners.dialog.username': 'Korisničko ime',
        'examiners.dialog.title': 'Titula',
        'examiners.dialog.email': 'Email',
        'examiners.dialog.password': 'Lozinka',
        'examiners.dialog.passwordHint': '(ostavite prazno za zadržavanje postojeće)',
        'examiners.dialog.passwordPlaceholder': 'Unesite novu lozinku za promjenu',
        'examiners.dialog.admin': 'Administrator',
        'examiners.dialog.accreditations': 'Akreditacije',
        'examiners.dialog.cancel': 'Odustani',
        'examiners.dialog.save': 'Spremi',
        'examiners.dialog.saving': 'Spremanje...',
        'examiners.dialog.fillRequired': 'Molimo ispunite sva obavezna polja',
        'examiners.dialog.emailRequired': 'Email je obavezan za nove ispitivače',
        'examiners.dialog.passwordRequired': 'Lozinka je obavezna za nove ispitivače',
        'examiners.dialog.passwordTooShort': 'Lozinka mora imati najmanje 6 znakova',
        'examiners.dialog.accreditationRequired': 'Molimo odaberite barem jednu akreditaciju',
        'examiners.dialog.saveFailed': 'Spremanje ispitivača nije uspjelo',
        'examiners.dialog.gender': 'Spol',
        'examiners.dialog.male': 'Muško',
        'examiners.dialog.female': 'Žensko',
        'examiners.deleteDialogTitle': 'Potvrdi brisanje',
        'examiners.deleteDialogMessage': 'Jeste li sigurni da želite obrisati ovog ispitivača?',
        'examiners.deleteWarning': 'Ova radnja se ne može poništiti.',
        'customers.title': 'Naručitelji',
        'customers.new': 'Novi naručitelj',
        'customers.search': 'Pretraži naručitelje...',
        'customers.workOrder': 'Radni nalog',
        'customers.name': 'Naziv',
        'customers.location': 'Lokacija',
        'customers.address': 'Adresa',
        'customers.actions': 'Akcije',
        'customers.loading': 'Učitavanje...',
        'customers.none': 'Nema pronađenih naručitelja.',
        'customers.showing': 'Prikazujem',
        'customers.to': 'do',
        'customers.of': 'od',
        'customers.results': 'rezultata',
        'customers.prev': 'Prethodna',
        'customers.next': 'Sljedeća',
        'customers.viewConstructions': 'Pogledaj gradilišta',
        'customers.edit': 'Uredi',
        'customers.deleteConfirm': 'Brisanje naručitelja će ukloniti sve povezane izvještaje. Nastaviti?',
        'reports.title': 'Izvještaji',
        'reports.dionica': 'Dionica',
        'reports.searchDionica': 'Traži dionicu...',
        'reports.type': 'Tip',
        'reports.status': 'Status',
        'reports.date': 'Datum',
        'reports.water': 'Voda',
        'reports.air': 'Zrak',
        'reports.satisfies': 'Zadovoljava',
        'reports.failed': 'Ne zadovoljava',
        'reports.noData': 'Nema izvještaja',
        'reports.deleteSelected': 'Obriši odabrano',
        'reports.newReport': 'Novi izvještaj',
        'reports.new': 'Novi',
        'reports.waterMethod': 'Metoda vodom',
        'reports.airMethod': 'Metoda zrakom',
        'reports.addSection': 'Dodaj sekciju',
        'reports.enterSectionName': 'Unesite naziv sekcije:',
        'reports.generateReports': 'Generiraj izvještaje',
        'reports.generate': 'Generiraj',
        'reports.exportSelected': 'Izvezi odabrano',
        'reports.exportAll': 'Izvezi sve',
        'reports.export': 'Izvezi',
        'reports.exportPdf': 'Izvezi PDF',
        'reports.edit': 'Uredi',
        'reports.delete': 'Obriši',
        'reports.draft': 'Nacrt',
        'reports.actions': 'Akcije',
        'common.all': 'Sve',
        'reports.manageViewReports': 'Upravljanje i pregled svih izvještaja.',
        'reports.deleteConfirm': 'Jeste li sigurni da želite obrisati ovaj izvještaj?',
        'reports.deleteSelectedConfirm': 'Jeste li sigurni da želite obrisati {count} odabran{plural}?',
        'reports.deleteSelectedFinal': 'Ova radnja se ne može poništiti. Obrisati {count} izvještaj{plural} trajno?',
        'reports.deleteSuccess': 'Izvještaj uspješno obrisan',
        'reports.deleteSelectedSuccess': 'Uspješno obrisan{plural} {count} izvještaj{plural}',
        'reports.exportSuccess': 'Izvještaj uspješno izvezen',
        'reports.noReports': 'Nema pronađenih izvještaja',
        'reports.reportsFromConstructions': 'Izvještaji se kreiraju iz gradilišta.',
    },
    en: {
        'nav.platform': 'Platform',
        'nav.history': 'History',
        'nav.examiners': 'Examiners',
        'nav.customers': 'Customers',
        'nav.settings': 'Settings',
        'nav.analytics': 'Analytics',
        'nav.help': 'Help',
        'nav.signOut': 'Sign Out',
        'settings.language': 'Language',
        'settings.languageDescription': 'Choose the interface language',
        'language.croatian': 'Croatian',
        'language.english': 'English',
        'history.title': 'History',
        'history.certifier': 'Certifier',
        'history.createdBy': 'Created By',
        'history.constructionPart': 'Construction Part',
        'history.formsCount': 'Forms Count',
        'history.creationTime': 'Creation Time',
        'history.open': 'Open',
        'history.remove': 'Remove',
        'history.searchPlaceholder': 'Search construction part...',
        'history.noDataTitle': 'No history found',
        'history.noDataDesc': 'Exported reports and their history will appear here.',
        'history.loading': 'Loading...',
        'history.allUsers': 'All Users',
        'history.page': 'Page',
        'history.of': 'of',
        'exportDetails.title': 'Export Details',
        'exportDetails.info': 'Information',
        'exportDetails.remarks': 'Remarks & Deviations',
        'exportDetails.certifier': 'Certifier',
        'exportDetails.createdBy': 'Created By',
        'exportDetails.examinationDate': 'Examination Date',
        'exportDetails.creationTime': 'Creation Time',
        'exportDetails.drainage': 'Drainage',
        'exportDetails.waterRemark': 'Water Remark',
        'exportDetails.waterDeviation': 'Water Deviation',
        'exportDetails.airRemark': 'Air Remark',
        'exportDetails.airDeviation': 'Air Deviation',
        'exportDetails.includedReports': 'Included Reports',
        'exportDetails.ordinal': 'Ordinal',
        'exportDetails.type': 'Type',
        'exportDetails.satisfies': 'Satisfies',
        'exportDetails.dionica': 'Dionica',
        'exportDetails.action': 'Action',
        'exportDetails.edit': 'Edit',
        'exportDetails.download': 'Download',
        'exportDetails.exportWord': 'Export Word',
        'exportDetails.exportPdf': 'Export PDF',
        'exportDetails.exportAllPdf': 'Export All PDF',
        'exportDetails.water': 'Water',
        'exportDetails.air': 'Air',
        'exportDetails.report': 'Report',
        'exportDetails.attachments': 'Attachments',
        'exportDetails.selectAll': 'Select All',
        'exportDetails.exporting': 'Exporting...',
        'exportDetails.downloading': 'Downloading...',
        'exportDetails.downloadFailed': 'Failed to download. Please try again.',
        'exportDetails.generatingPdf': 'Generating PDF export...',
        'exportDetails.generatingWord': 'Generating Word document...',
        'exportDetails.exportFailed': 'Failed to export. Please try again.',
        'exportDetails.wordFailed': 'Failed to export Word document. Please try again.',
        'dashboard.welcome': 'Hello',
        'dashboard.ready': 'Your generator is ready.',
        'dashboard.totalCustomers': 'Total Customers',
        'dashboard.activeSites': 'Active Sites',
        'dashboard.totalReports': 'Total Reports',
        'dashboard.customersTable': 'Customers',
        'dashboard.search': 'Search...',
        'dashboard.addCustomer': 'Add customer',
        'dashboard.workOrder': 'Work Order',
        'dashboard.customer': 'Customer',
        'dashboard.activeOrders': 'Active Work Orders',
        'dashboard.none': 'None',
        'dashboard.showMore': 'Show more',
        'dashboard.showLess': 'Show less',
        'dashboard.loading': 'Loading...',
        'dashboard.noCustomers': 'No customers found',
        'dashboard.topCustomers': 'Top Customers',
        'dashboard.examiners': 'Examiners',
        'dashboard.today': 'Today',
        'dashboard.thisWeek': 'This week',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.you': 'You',
        'examiners.title': 'Examiners',
        'examiners.subtitle': 'Manage examiners and their accreditations.',
        'examiners.add': 'Add Examiner',
        'examiners.search': 'Search examiners...',
        'examiners.fullName': 'Full Name',
        'examiners.username': 'Username',
        'examiners.email': 'Email',
        'examiners.accreditations': 'Accreditations',
        'examiners.actions': 'Actions',
        'examiners.loading': 'Loading...',
        'examiners.noneFound': 'No examiners found',
        'examiners.noneDesc': 'Add examiners to manage their accreditations and assignments.',
        'examiners.accessDenied': 'Access Denied',
        'examiners.accessDesc': 'Only administrators can manage examiners.',
        'examiners.admin': 'Administrator',
        'examiners.removeConfirm': 'Are you sure you want to remove this examiner?',
        'examiners.dialog.new': 'New Examiner',
        'examiners.dialog.edit': 'Edit Examiner',
        'examiners.dialog.firstName': 'First Name',
        'examiners.dialog.lastName': 'Last Name',
        'examiners.dialog.username': 'Username',
        'examiners.dialog.title': 'Title',
        'examiners.dialog.email': 'Email',
        'examiners.dialog.password': 'Password',
        'examiners.dialog.passwordHint': '(leave empty to keep current)',
        'examiners.dialog.passwordPlaceholder': 'Enter new password to change',
        'examiners.dialog.admin': 'Administrator',
        'examiners.dialog.accreditations': 'Accreditations',
        'examiners.dialog.cancel': 'Cancel',
        'examiners.dialog.save': 'Save',
        'examiners.dialog.saving': 'Saving...',
        'examiners.dialog.fillRequired': 'Please fill in all required fields',
        'examiners.dialog.emailRequired': 'Email is required for new examiners',
        'examiners.dialog.passwordRequired': 'Password is required for new examiners',
        'examiners.dialog.passwordTooShort': 'Password must be at least 6 characters long',
        'examiners.dialog.accreditationRequired': 'Please select at least one accreditation',
        'examiners.dialog.saveFailed': 'Failed to save examiner',
        'examiners.dialog.gender': 'Gender',
        'examiners.dialog.male': 'Male',
        'examiners.dialog.female': 'Female',
        'examiners.deleteDialogTitle': 'Confirm Deletion',
        'examiners.deleteDialogMessage': 'Are you sure you want to delete this examiner?',
        'examiners.deleteWarning': 'This action cannot be undone.',
        'customers.title': 'Customers',
        'customers.new': 'New Customer',
        'customers.search': 'Search customers...',
        'customers.workOrder': 'Work Order',
        'customers.name': 'Name',
        'customers.location': 'Location',
        'customers.address': 'Address',
        'customers.actions': 'Actions',
        'customers.loading': 'Loading...',
        'customers.none': 'No customers found.',
        'customers.showing': 'Showing',
        'customers.to': 'to',
        'customers.of': 'of',
        'customers.results': 'results',
        'customers.prev': 'Previous',
        'customers.next': 'Next',
        'customers.viewConstructions': 'View Constructions',
        'customers.edit': 'Edit',
        'customers.deleteConfirm': 'Removing this customer will also remove all related reports. Continue?',
        'reports.title': 'Reports',
        'reports.dionica': 'Dionica',
        'reports.searchDionica': 'Search dionica...',
        'reports.type': 'Type',
        'reports.status': 'Status',
        'reports.date': 'Date',
        'reports.water': 'Water',
        'reports.air': 'Air',
        'reports.satisfies': 'Satisfies',
        'reports.failed': 'Failed',
        'reports.noData': 'No reports found',
        'reports.deleteSelected': 'Delete Selected',
        'reports.newReport': 'New Report',
        'reports.new': 'New',
        'reports.waterMethod': 'Water Method',
        'reports.airMethod': 'Air Method',
        'reports.addSection': 'Add Section',
        'reports.enterSectionName': 'Enter section name:',
        'reports.generateReports': 'Generate Reports',
        'reports.generate': 'Generate',
        'reports.exportSelected': 'Export Selected',
        'reports.exportAll': 'Export All',
        'reports.export': 'Export',
        'reports.exportPdf': 'Export PDF',
        'reports.edit': 'Edit',
        'reports.delete': 'Delete',
        'reports.draft': 'Draft',
        'reports.actions': 'Actions',
        'common.all': 'All',
        'reports.manageViewReports': 'Manage and view all test reports.',
        'reports.deleteConfirm': 'Are you sure you want to delete this report?',
        'reports.deleteSelectedConfirm': 'Are you sure you want to delete {count} selected report{plural}?',
        'reports.deleteSelectedFinal': 'This action cannot be undone. Delete {count} report{plural} permanently?',
        'reports.deleteSuccess': 'Report deleted successfully',
        'reports.deleteSelectedSuccess': 'Successfully deleted {count} report{plural}',
        'reports.exportSuccess': 'Report exported successfully',
        'reports.noReports': 'No reports found',
        'reports.reportsFromConstructions': 'Reports are created from construction sites.',
    }
};

// Final clean overrides and additions
Object.assign(translations.hr, {
    'customers.postalCode': 'Poštanski broj',
    'customers.dateAdded': 'Datum dodavanja',
    'customers.save': 'Spremi',
    'customers.loadingForm': 'Učitavanje...',
    'customers.newTitle': 'Novi naručitelj',
    'customers.editTitle': 'Uredi naručitelja',
    'customers.placeholderWork': 'npr. 2023-001',
    'customers.placeholderName': 'Naziv naručitelja',
    'customers.placeholderLocation': 'Grad / Regija',
    'customers.placeholderAddress': 'Ulica i broj',
    'customers.placeholderPostal': 'Poštanski broj',
    'customers.deleteConfirm': 'Brisanje naručitelja će ukloniti sve povezane izvještaje. Nastaviti?',
    'customers.search': 'Pretraži naručitelje...',
    'customers.viewConstructions': 'Pogledaj gradilišta',
    'customers.next': 'Sljedeća',
    'constructions.title': 'Gradilišta',
    'constructions.new': 'Novo gradilište',
    'constructions.for': 'za',
    'constructions.search': 'Pretraži gradilišta...',
    'constructions.workOrder': 'Radni nalog',
    'constructions.name': 'Naziv',
    'constructions.location': 'Lokacija',
    'constructions.dateAdded': 'Datum dodavanja',
    'constructions.actions': 'Akcije',
    'constructions.viewReports': 'Pogledaj izvještaje',
    'constructions.edit': 'Uredi',
    'constructions.delete': 'Obriši',
    'constructions.deleteConfirm': 'Jeste li sigurni da želite obrisati ovo gradilište? Ovo će obrisati sve povezane izvještaje.',
    'constructions.none': 'Nema gradilišta.',
    'constructions.loading': 'Učitavanje...',
    'constructions.save': 'Spremi',
    'reports.date': 'Datum',
    'reports.type': 'Tip',
    'reports.dionica': 'Dionica',
    'reports.draft': 'Skica',
    'reports.status': 'Status',
    'reports.actions': 'Akcije',
    'reports.exportPdf': 'Izvoz PDF',
    'reports.edit': 'Uredi',
    'reports.delete': 'Obriši',
    'reports.noData': 'Nema izvješća za ovo gradilište.',
    'reports.satisfies': 'Zadovoljava',
    'reports.failed': 'Ne zadovoljava',
    'reports.new': 'Novo',
    'reports.generate': 'Generiraj',
    'reports.export': 'Izvoz'
});

Object.assign(translations.en, {
    'constructions.title': 'Construction Sites',
    'constructions.new': 'New Construction',
    'constructions.for': 'for',
    'constructions.search': 'Search constructions...',
    'constructions.workOrder': 'Work Order',
    'constructions.name': 'Name',
    'constructions.location': 'Location',
    'constructions.actions': 'Actions',
    'constructions.viewReports': 'View Reports',
    'constructions.edit': 'Edit',
    'constructions.delete': 'Delete',
    'constructions.deleteConfirm': 'Are you sure you want to delete this construction site? This will also delete all associated reports.',
    'constructions.none': 'No construction sites found.',
    'constructions.loading': 'Loading...',
    'constructions.save': 'Save',
    'constructions.newTitle': 'New Construction',
    'constructions.editTitle': 'Edit Construction',
    'constructions.placeholderWork': 'e.g., 2023-001-A',
    'constructions.placeholderName': 'Construction Site Name',
    'constructions.placeholderLocation': 'Site Location',
    'constructions.dateAdded': 'Date Added',
    'reports.title': 'Reports',
    'reports.deleteSelected': 'Delete Selected',
    'reports.newReport': 'New Report',
    'reports.delete': 'Delete',
    'reports.noData': 'No reports found for this construction site.',
    'reports.satisfies': 'Satisfies',
    'reports.failed': 'Failed'
});

Object.assign(translations.en, {
    'customers.postalCode': 'Postal Code',
    'customers.dateAdded': 'Date Added',
    'customers.save': 'Save',
    'customers.loadingForm': 'Loading...',
    'customers.newTitle': 'New Customer',
    'customers.editTitle': 'Edit Customer',
    'customers.placeholderWork': 'e.g., 2023-001',
    'customers.placeholderName': 'Customer Name',
    'customers.placeholderLocation': 'City / Region',
    'customers.placeholderAddress': 'Street Address',
    'customers.placeholderPostal': 'Postal Code',
    'customers.deleteConfirm': 'Removing this customer will also remove all related reports. Continue?',
    'customers.search': 'Search customers...',
    'customers.viewConstructions': 'View Constructions',
    'customers.next': 'Next',
    'constructions.title': 'Construction Sites',
    'constructions.for': 'for',
    'constructions.new': 'New Construction',
    'constructions.search': 'Search constructions...',
    'constructions.workOrder': 'Work Order',
    'constructions.name': 'Name',
    'constructions.location': 'Location',
    'constructions.actions': 'Actions',
    'constructions.viewReports': 'View Reports',
    'constructions.edit': 'Edit',
    'constructions.delete': 'Delete',
    'constructions.deleteConfirm': 'Are you sure you want to delete this construction site? This will also delete all associated reports.',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.deleteConfirm': 'Are you sure you want to delete?',
    'common.select': 'Select',
    'common.optional': '(optional)',
    'constructions.none': 'No construction sites found.'
});

// Clean overrides for constructions (HR/EN)
Object.assign(translations.hr, {
    'constructions.loading': 'Učitavanje...',
    'constructions.save': 'Spremi',
    'constructions.newTitle': 'Novo gradilište',
    'constructions.editTitle': 'Uredi gradilište',
    'constructions.placeholderWork': 'npr. 2023-001-A',
    'constructions.placeholderName': 'Naziv gradilišta',
    'constructions.placeholderLocation': 'Lokacija gradilišta'
});

Object.assign(translations.en, {
    'constructions.loading': 'Loading...',
    'constructions.save': 'Save',
    'constructions.newTitle': 'New Construction',
    'constructions.editTitle': 'Edit Construction',
    'constructions.placeholderWork': 'e.g., 2023-001-A',
    'constructions.placeholderName': 'Construction Site Name',
    'constructions.placeholderLocation': 'Site Location'
});

// Settings / Materials translations
Object.assign(translations.hr, {
    'materials.shaftTitle': 'Materijali za okna',
    'materials.pipeTitle': 'Materijali za cijevi',
    'materials.addShaft': 'Dodaj materijal okna',
    'materials.addPipe': 'Dodaj materijal cijevi',
    'materials.newShaft': 'Dodaj novi materijal okna',
    'materials.newPipe': 'Dodaj novi materijal cijevi',
    'materials.editShaft': 'Uredi materijal okna',
    'materials.editPipe': 'Uredi materijal cijevi',
    'materials.namePlaceholder': 'Naziv materijala',
    'materials.save': 'Spremi',
    'materials.cancel': 'Odustani',
    'materials.noneShaftTitle': 'Nema materijala za okna',
    'materials.nonePipeTitle': 'Nema materijala za cijevi',
    'materials.noneDesc': 'Dodajte materijale kako biste ih koristili u izvještajima.',
    'materials.edit': 'Uredi',
    'materials.remove': 'Ukloni',
    'materials.added': 'Materijal dodan.',
    'materials.updated': 'Materijal ažuriran.',
    'materials.removed': 'Materijal uklonjen.',
    'materials.deleteConfirm': 'Jeste li sigurni da želite ukloniti ovaj materijal?',
    'materials.restricted': 'Upravljanje materijalima je ograničeno na administratore.',
    'materials.inUseError': 'Materijal se koristi u izvještajima pa ga nije moguće ukloniti.',
    'materials.deleteDialogTitle': 'Potvrdi brisanje',
    'materials.deleteDialogMessage': 'Jeste li sigurni da želite obrisati ovaj materijal?',
    'materials.materialType': 'Vrsta materijala',
    'materials.materialName': 'Naziv materijala',
    'materials.deleteWarning': 'Ova radnja se ne može poništiti.',
    'materials.confirmDelete': 'Obriši materijal',
    'materials.shaftSingular': 'Materijal za okna',
    'materials.pipeSingular': 'Materijal za cijevi'
});

Object.assign(translations.en, {
    'materials.shaftTitle': 'Shaft Materials',
    'materials.pipeTitle': 'Pipe Materials',
    'materials.addShaft': 'Add shaft material',
    'materials.addPipe': 'Add pipe material',
    'materials.newShaft': 'Add new shaft material',
    'materials.newPipe': 'Add new pipe material',
    'materials.editShaft': 'Edit shaft material',
    'materials.editPipe': 'Edit pipe material',
    'materials.namePlaceholder': 'Material name',
    'materials.save': 'Save',
    'materials.cancel': 'Cancel',
    'materials.noneShaftTitle': 'No shaft materials found',
    'materials.nonePipeTitle': 'No pipe materials found',
    'materials.noneDesc': 'Add materials to use them in reports.',
    'materials.edit': 'Edit',
    'materials.remove': 'Remove',
    'materials.added': 'Material added successfully.',
    'materials.updated': 'Material updated successfully.',
    'materials.removed': 'Material removed successfully.',
    'materials.deleteConfirm': 'Are you sure you want to remove this material?',
    'materials.restricted': 'Material management is restricted to administrators.',
    'materials.inUseError': 'Material is used in reports and cannot be removed.',
    'materials.deleteDialogTitle': 'Confirm Deletion',
    'materials.deleteDialogMessage': 'Are you sure you want to delete this material?',
    'materials.materialType': 'Material type',
    'materials.materialName': 'Material name',
    'materials.deleteWarning': 'This action cannot be undone.',
    'materials.confirmDelete': 'Delete Material',
    'materials.shaftSingular': 'Shaft material',
    'materials.pipeSingular': 'Pipe material'
});

// Settings appearance translations
Object.assign(translations.hr, {
    'settings.appearance': 'Izgled',
    'settings.theme': 'Tema',
    'settings.themeDesc': 'Odaberite način prikaza',
    'settings.light': 'Svijetla',
    'settings.dark': 'Tamna',
    'settings.system': 'Sustav',
    'settings.primaryColor': 'Primarna boja',
    'settings.primaryColorDesc': 'Odaberite primarnu boju aplikacije',
    'settings.cacheManagement': 'Upravljanje predmemorijom',
    'settings.cacheDescription': 'Obriši predmemoriju za rješavanje problema ili oslobađanje prostora',
    'settings.clearCache': 'Obriši predmemoriju',
    'settings.clearing': 'Brisanje...',
    'settings.cacheCleared': 'Predmemorija uspješno obrisana',
    'settings.cacheWarning': 'Ovo će obrisati sve spremljene podatke osim vaše prijave. Stranica će se ponovno učitati.'
});

Object.assign(translations.en, {
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Choose your display mode',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.primaryColor': 'Primary Color',
    'settings.primaryColorDesc': 'Choose the app\'s primary color',
    'settings.cacheManagement': 'Cache Management',
    'settings.cacheDescription': 'Clear cache to fix issues or free up space',
    'settings.clearCache': 'Clear Cache',
    'settings.clearing': 'Clearing...',
    'settings.cacheCleared': 'Cache cleared successfully',
    'settings.cacheWarning': 'This will clear all cached data except your login. The page will reload.'
});

// Analytics translations
Object.assign(translations.hr, {
    'analytics.title': 'Analitika',
    'analytics.subtitle': 'Pregled prolaznosti i trajanja ispitivanja.',
    'analytics.passFail': 'Prolaz vs. pad',
    'analytics.pass': 'Prolaz',
    'analytics.fail': 'Pad',
    'analytics.passRate': 'Postotak prolaza',
    'analytics.avgDuration': 'Prosječno trajanje ispitivanja',
    'analytics.water': 'Voda',
    'analytics.air': 'Zrak',
    'analytics.loading': 'Učitavanje analitike...',
    'analytics.error': 'Neuspjelo učitavanje analitike. Pokušajte ponovo.',
    'analytics.totalReports': 'Ukupno izvještaja',
    'analytics.activeCustomers': 'Ukupno naručitelja',
    'analytics.constructionSites': 'Ukupno gradilišta',
    'analytics.recentActivity': 'Aktivni izvještaji',
    'analytics.thisWeek': 'Zadnjih 7 dana',
    'profile.title': 'Moj Profil',
    'profile.subtitle': 'Upravljajte svojim osobnim podacima i postavkama.',
    'profile.changePhoto': 'Kliknite za promjenu fotografije',
    'profile.avatarUploaded': 'Profilna slika uspješno ažurirana',
    'profile.avatarUploadFailed': 'Neuspjelo učitavanje slike',
    'profile.saved': 'Profil uspješno spremljen',
    'profile.saveFailed': 'Spremanje profila nije uspjelo',
    'profile.emailReadOnly': 'Email adresu nije moguće mijenjati. Kontaktirajte administratora za promjenu.',
    'reports.form.notesSection': 'Bilješke',
    'reports.form.calculatedResults': 'Izračunati rezultati',
    'reports.form.nextStep': 'Sljedeći korak',
    'reports.form.saveReport': 'Spremi izvještaj',
    'reports.form.saveSuccess': 'Izvještaj spremljen. Spreman za novi unos.',
    'reports.form.loadError': 'Neuspjelo učitavanje izvještaja',
    'reports.form.temperature': 'Temperatura (°C)',
    'reports.form.paneWidthM': 'Širina okna (m)',
    'reports.form.paneLengthM': 'Dužina okna (m)',
    'reports.form.pipeLengthM': 'Dužina cijevi (m)',
    'reports.form.startPressure': 'Početni tlak (mbar)',
    'reports.form.endPressure': 'Završni tlak (mbar)',
    'reports.form.startTime': 'Početak',
    'reports.form.allowedLoss': 'Dopušteni gubitak',
    'reports.form.schemeA': 'Shema A – Ispitivanje okna',
    'reports.form.schemeB': 'Shema B – Ispitivanje okna i cijelovoda',
    'reports.form.schemeC': 'Shema C – Ispitivanje cijelovoda',
    'reports.form.schemeD': 'Shema D – Ispitivanje slivnika',
    'reports.form.schemeE': 'Shema E – Ispitivanje slivnika i cijelovoda',
    'reports.form.paneWidthCm': 'Širina okna (cm)',
    'reports.form.paneLengthCm': 'Dužina okna (cm)',
    'reports.form.gullyWidth': 'Širina slivnika (cm)',
    'reports.form.gullyLength': 'Dužina slivnika (cm)',
    'reports.form.channelWidth': 'Širina kanala (cm)',
    'reports.form.channelLength': 'Dužina kanala (cm)',
    'reports.form.pipeLengthMeters': 'Dužina cijevi (m)',
    'reports.form.depositionalHeight': 'Visina taloženja (m)',
    'reports.form.startWaterLevel': 'Početna razina vode (mm)',
    'reports.form.endWaterLevel': 'Završna razina vode (mm)',
    'reports.form.totalWettedArea': 'Ukupna mokra površina',
    'reports.form.wettedShaftSurface': 'Mokra površina okna',
    'reports.form.wettedPipeSurface': 'Mokra površina cijevi',
    'reports.form.allowedLossLiters': 'Dopušteni gubitak (l)',
    'reports.form.allowedLossMm': 'Dopušteni gubitak (mm)',
    'reports.form.resultUnit': 'l/m²'
});

// Report method labels
Object.assign(translations.hr, {
    'reports.waterMethod': 'Metoda vode',
    'reports.airMethod': 'Metoda zraka'
});
Object.assign(translations.en, {
    'reports.waterMethod': 'Water Method',
    'reports.airMethod': 'Air Method'
});

// Calendar translations (EN)
Object.assign(translations.en, {
    'nav.calendar': 'Calendar',
    'calendar.title': 'Examination Calendar',
    'calendar.subtitle': 'View and manage examination appointments.',
    'calendar.newEvent': 'New Appointment',
    'calendar.editEvent': 'Edit Appointment',
    'calendar.eventTitle': 'Title',
    'calendar.start': 'Start',
    'calendar.end': 'End',
    'calendar.examiners': 'Examiners',
    'calendar.customer': 'Customer',
    'calendar.construction': 'Construction Site',
    'calendar.description': 'Description',
    'calendar.adminOnlyAssign': 'Only admins can assign other examiners.',
    'calendar.deleteDialogTitle': 'Confirm Deletion',
    'calendar.deleteDialogMessage': 'Are you sure you want to delete this appointment?',
    'calendar.deleteWarning': 'This action cannot be undone.',
    'calendar.next': 'Next',
    'calendar.previous': 'Back',
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.agenda': 'Agenda',
    'calendar.date': 'Date',
    'calendar.time': 'Time',
    'calendar.event': 'Event',
    'calendar.noEvents': 'No events in this range'
});

// Export dialog translations
Object.assign(translations.hr, {
    'export.optionsTitle': 'Opcije izvoza izvještaja',
    'export.selectReports': 'Odaberite izvještaje za izvoz',
    'export.selectAll': 'Odaberi sve',
    'export.deselectAll': 'Poništi odabir',
    'export.selected': 'odabrano',
    'export.constructionPart': 'Dio Građevine',
    'export.constructionPartPlaceholder': 'npr. Zgrada 1',
    'export.drainage': 'Drenaža',
    'export.drainagePlaceholder': 'Tip sustava...',
    'export.remark': 'Napomena',
    'export.remarkPlaceholder': 'Napomene...',
    'export.deviation': 'Odstupanje',
    'export.deviationPlaceholder': 'Odstupanja od norme...',
    'export.certifierName': 'Certifikator',
    'export.certifierPlaceholder': 'Ime i prezime certifikatora',
    'export.attachments': 'Prilozi',
    'export.attachmentsHelp': 'Dodajte fotografije ili PDF dokumente koji će biti priloženi izvještaju',
    'export.cancel': 'Odustani',
    'export.exporting': 'Izvoz u tijeku...',
    'export.exportReport': 'Izvezi izvještaj'
});

Object.assign(translations.en, {
    'export.optionsTitle': 'Export Report Options',
    'export.selectReports': 'Select Reports to Export',
    'export.selectAll': 'Select All',
    'export.deselectAll': 'Deselect All',
    'export.selected': 'selected',
    'export.constructionPart': 'Construction Part',
    'export.constructionPartPlaceholder': 'e.g. Phase 1',
    'export.drainage': 'Drainage',
    'export.drainagePlaceholder': 'System type...',
    'export.remark': 'Remark',
    'export.remarkPlaceholder': 'Notes...',
    'export.deviation': 'Deviation',
    'export.deviationPlaceholder': 'Norm deviations...',
    'export.certifierName': 'Certifier Name',
    'export.certifierPlaceholder': 'Name of the person certifying...',
    'export.attachments': 'Attachments',
    'export.attachmentsHelp': 'Add photos or PDFs to attach to the report',
    'export.cancel': 'Cancel',
    'export.exporting': 'Exporting...',
    'export.exportReport': 'Export Report'
});

// Clean HR overrides for report forms (accents)
Object.assign(translations.hr, {
    'reports.form.editTitle': 'Uredi izvještaj',
    'reports.form.generalInfo': 'Opće informacije',
    'reports.form.notesSection': 'Bilješke',
    'reports.form.calculatedResults': 'Izračunati rezultati',
    'reports.form.nextStep': 'Sljedeći korak',
    'reports.form.saveReport': 'Spremi izvještaj',
    'reports.form.saveSuccess': 'Izvještaj spremljen. Spreman za novi unos.',
    'reports.form.loadError': 'Neuspjelo učitavanje izvještaja',
    'reports.form.temperature': 'Temperatura (°C)',
    'reports.form.paneWidthM': 'Širina okna (m)',
    'reports.form.paneLengthM': 'Dužina okna (m)',
    'reports.form.pipeLengthM': 'Dužina cijevi (m)',
    'reports.form.startPressure': 'Početni tlak (mbar)',
    'reports.form.endPressure': 'Završni tlak (mbar)',
    'reports.form.startTime': 'Početak',
    'reports.form.allowedLoss': 'Dopušteni gubitak',
    'reports.form.schemeA': 'Shema A – Ispitivanje okna',
    'reports.form.schemeB': 'Shema B – Ispitivanje okna i cijelovoda',
    'reports.form.schemeC': 'Shema C – Ispitivanje cijelovoda',
    'reports.form.schemeD': 'Shema D – Ispitivanje slivnika',
    'reports.form.schemeE': 'Shema E – Ispitivanje slivnika i cijelovoda',
    'reports.form.paneWidthCm': 'Širina okna (cm)',
    'reports.form.paneLengthCm': 'Dužina okna (cm)',
    'reports.form.gullyWidth': 'Širina slivnika (cm)',
    'reports.form.gullyLength': 'Dužina slivnika (cm)',
    'reports.form.channelWidth': 'Širina kanala (cm)',
    'reports.form.channelLength': 'Dužina kanala (cm)',
    'reports.form.pipeLengthMeters': 'Dužina cijevi (m)',
    'reports.form.depositionalHeight': 'Visina taloženja (m)',
    'reports.form.startWaterLevel': 'Početna razina vode (mm)',
    'reports.form.endWaterLevel': 'Završna razina vode (mm)',
    'reports.form.totalWettedArea': 'Ukupna mokra površina',
    'reports.form.wettedShaftSurface': 'Mokra površina okna',
    'reports.form.wettedPipeSurface': 'Mokra površina cijevi',
    'reports.form.allowedLossLiters': 'Dopušteni gubitak (l)',
    'reports.form.allowedLossMm': 'Dopušteni gubitak (mm)',
    'reports.form.resultUnit': 'l/m²'
});

// Help translations
Object.assign(translations.hr, {
    'help.title': 'Pomoć',
    'help.comingSoon': 'Pomoć i dokumentacija stižu uskoro...',
    'help.tabs.faq': 'Najčešća pitanja',
    'help.tabs.support': 'Podrška',
    'help.support.title': 'Zahtjev za podršku',
    'help.support.subtitle': 'Pošaljite nam svoj zahtjev za promjenom, prijavu greške ili prijedlog nove značajke',
    'help.support.requestType': 'Tip zahtjeva',
    'help.support.requestType.placeholder': 'Odaberite tip zahtjeva',
    'help.support.requestType.changeRequest': 'Zahtjev za promjenom',
    'help.support.requestType.bug': 'Prijava greške',
    'help.support.requestType.feature': 'Prijedlog značajke',
    'help.support.title.label': 'Naslov',
    'help.support.title.placeholder': 'Kratki opis problema ili zahtjeva',
    'help.support.description.label': 'Opis',
    'help.support.description.placeholder': 'Detaljno opišite svoj zahtjev, grešku ili prijedlog...',
    'help.support.attachments.label': 'Prilozi',
    'help.support.attachments.help': 'Priložite slike ili dokumente (maks. 5 MB po datoteci)',
    'help.support.attachments.button': 'Odaberi datoteke',
    'help.support.attachments.selected': 'odabrano',
    'help.support.submit': 'Pošalji zahtjev',
    'help.support.submitting': 'Šaljem...',
    'help.support.success': 'Zahtjev uspješno poslan!',
    'help.support.error': 'Greška prilikom slanja zahtjeva. Pokušajte ponovno.',
    'help.support.validation.requestType': 'Molimo odaberite tip zahtjeva',
    'help.support.validation.title': 'Molimo unesite naslov',
    'help.support.validation.description': 'Molimo unesite opis',
    'help.support.validation.fileSize': 'Datoteka je prevelika (maks. 5 MB)',
});
Object.assign(translations.en, {
    'help.title': 'Help',
    'help.comingSoon': 'Help and documentation coming soon...',
    'help.tabs.faq': 'FAQ',
    'help.tabs.support': 'Support',
    'help.support.title': 'Support Request',
    'help.support.subtitle': 'Send us your change request, bug report, or feature suggestion',
    'help.support.requestType': 'Request Type',
    'help.support.requestType.placeholder': 'Select request type',
    'help.support.requestType.changeRequest': 'Change Request',
    'help.support.requestType.bug': 'Bug Report',
    'help.support.requestType.feature': 'Feature Request',
    'help.support.title.label': 'Title',
    'help.support.title.placeholder': 'Brief description of the issue or request',
    'help.support.description.label': 'Description',
    'help.support.description.placeholder': 'Describe your request, bug, or suggestion in detail...',
    'help.support.attachments.label': 'Attachments',
    'help.support.attachments.help': 'Attach images or documents (max. 5 MB per file)',
    'help.support.attachments.button': 'Choose files',
    'help.support.attachments.selected': 'selected',
    'help.support.submit': 'Submit Request',
    'help.support.submitting': 'Sending...',
    'help.support.success': 'Request sent successfully!',
    'help.support.error': 'Error sending request. Please try again.',
    'help.support.validation.requestType': 'Please select a request type',
    'help.support.validation.title': 'Please enter a title',
    'help.support.validation.description': 'Please enter a description',
    'help.support.validation.fileSize': 'File is too large (max. 5 MB)',
});

// Common
Object.assign(translations.hr, {
    'common.back': 'Natrag'
});

// Common translations (HR)
Object.assign(translations.hr, {
    'common.cancel': 'Odustani',
    'common.save': 'Spremi',
    'common.add': 'Dodaj',
    'common.search': 'Traži',
    'common.filter': 'Filtriraj',
    'common.export': 'Izvezi',
    'common.import': 'Uvezi',
    'common.loading': 'Učitavanje...',
    'common.error': 'Greška',
    'common.success': 'Uspjeh',
    'common.confirm': 'Potvrdi',
    'common.close': 'Zatvori',
    'common.next': 'Sljedeći',
    'common.previous': 'Prethodni',
    'common.deleteConfirm': 'Jeste li sigurni da želite obrisati?',
    'common.select': 'Odaberi',
    'common.optional': '(neobavezno)'
});
Object.assign(translations.en, {
    'common.back': 'Back',
    'common.edit': 'Edit',
    'common.delete': 'Delete'
});

// Calendar translations (HR)
Object.assign(translations.hr, {
    'nav.calendar': 'Kalendar',
    'calendar.title': 'Kalendar Ispitivanja',
    'calendar.subtitle': 'Pregled i upravljanje terminima ispitivanja.',
    'calendar.newEvent': 'Novi Termin',
    'calendar.editEvent': 'Uredi Termin',
    'calendar.eventTitle': 'Naslov',
    'calendar.start': 'Početak',
    'calendar.end': 'Kraj',
    'calendar.examiners': 'Ispitivači',
    'calendar.customer': 'Naručitelj',
    'calendar.construction': 'Gradilište',
    'calendar.description': 'Opis',
    'calendar.adminOnlyAssign': 'Samo administratori mogu dodijeliti druge ispitivače.',
    'calendar.deleteDialogTitle': 'Potvrdi brisanje',
    'calendar.deleteDialogMessage': 'Jeste li sigurni da želite obrisati ovaj termin?',
    'calendar.deleteWarning': 'Ova radnja se ne može poništiti.',
    'calendar.next': 'Sljedeći',
    'calendar.previous': 'Prethodni',
    'calendar.today': 'Danas',
    'calendar.month': 'Mjesec',
    'calendar.week': 'Tjedan',
    'calendar.day': 'Dan',
    'calendar.agenda': 'Raspored',
    'calendar.date': 'Datum',
    'calendar.time': 'Vrijeme',
    'calendar.event': 'Događaj',
    'calendar.noEvents': 'Nema događaja u ovom rasponu'
});

interface LanguageContextValue {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const stored = localStorage.getItem('language') as Language | null;
        return stored || 'hr';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
    }, [language]);

    const setLanguage = (lang: Language) => setLanguageState(lang);

    const t = (key: string) => translations[language][key] || translations.hr[key] || key;

    const value = useMemo(() => ({ language, setLanguage, t }), [language]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
    return ctx;
};








